### ISSUE TITLE
Question about state of Security V1.3.1

### ISSUE THREAD

**Issue by khevessy** [riebl/vanetza#192]
Hi @riebl,

I wanted to ask about state of the https://github.com/riebl/vanetza/tree/sec_v2_namespace branch. I know it is based on pull request #130. We want to use Vanetza with newer security and so my question is, are you still working on merging it to the main branch? Also, in how usable state the branch is? I am not pressuring you, just to ask how the progress is and if we should work on this ourselves or wait until you implement this.

Thanks and regards,
Karel

**Comment by riebl** [comment]
Hi @khevessy,

I have finally merged the *sec_v2_namespace* branch into *master* and also implemented verification of v3 secured messages. The verification process is not yet complete, e.g. certificates are not thoroughly validated. However, valid messages are passed up to the applications now and are not dropped anymore.

**Comment by lo-hei** [comment]
Hey @riebl ,
thank you very much for this work. I'm excited and looking forward to working with it.
@khevessy Do you have any plans to integrate it into your Repo (for Autotalks) in the near future? I tried it by myself but sadly i could not get it running due to some bugs. 

(Problems found and resolved: The current security.cpp in socktap is using the wrong StraightVerifyService Import,
Problem which could not be solved, yet: Vanetza is compiled but when running on the Autotalks-Device i got  an Assertion Fail from /include/boost/variant/detail/forced_return.hpp:38) 

Thank you both for the great work.

**Comment by riebl** [comment]
Oops, I have just fixed the broken *socktap* and *benchmark* builds. Sorry for that trouble.
Can you share some more details about the assertion failure?

**Comment by khevessy** [comment]
@riebl Sorry but didn't you forgot to push the code? I am eager to try it
